[tools]
go = "1.21.3"
"github:lucasew/workspaced" = "v0.2.1"

[tasks]
lint = "workspaced codebase lint"
fmt = "workspaced codebase format"

[tasks.test]
depends = ["test:*"]

[tasks."test:go"]
run = """
if [ -f go.mod ]; then
  go test -v ./...
else
  echo 'No go.mod found, skipping test'
fi
"""

[tasks.codegen]
depends = ["codegen:*"]

[tasks."codegen:go"]
run = """
if [ -f go.mod ]; then
  go generate ./...
else
  echo 'No go.mod found, skipping codegen'
fi
"""

[tasks.install]
depends = ["install:*"]

[tasks."install:go"]
run = """
if [ -f go.mod ]; then
  go mod download
else
  echo 'No go.mod found, skipping download'
fi
"""

[tasks.ci]
depends = ["lint", "test"]
