name: Autorelease

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Environment
        run: |
          echo "Debugging Environment..."
          ls -R
          pwd
          git status

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true

      - name: Debug Go Environment
        run: |
          go version
          go env

      - name: Install dependencies
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Check for changes and create PR if needed
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update generated code"
          title: "chore: update generated code"
          body: "Automated PR to update generated code."
          branch: "chore/codegen-update"

      - name: Run Checks
        run: mise run check

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: mise run build

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} dist/* --generate-notes

      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: dist/
